### ISSUE TITLE
Can't schedule a boat ride

### ISSUE THREAD

**Issue by proxima** [danielkim85/chrispaulsboat#1]
Hi,

I click the calendar but there are no popups etc for me to schedule a boat ride. I would like to ride Chris Paul's fabled boat. Please help

**Comment by danielkim85** [comment]
Per this logic here:
https://github.com/danielkim85/chrispaulsboat/blob/master/python/common.py#L15

you must be T-Pain in order to set up a boat ride.
Being friends with T-Pain does not grant you the right to initiate an event, but on the right to attend one.

**Comment by proxima** [comment]
ah yes, t-pain needs to make events before i can consider joining them. makes sense. thanks awesome dev

**Comment by danielkim85** [comment]
Issue for not being able to sign up was actually due to config.py being wiped out and now addressed.
Additionally, you've been added to the t-pain group so you can verify the fix.

**Comment by proxima** [comment]
works.
